### ISSUE TITLE
cpcs review private from Larry

### ISSUE THREAD

**Issue by tradesouthwest** [xxsimoxx/xsx-shorten-it#1]
FILE: /var/www/html/cp-plugin-review/xsx-shorten-it/xsx-shorten-it.php
--------------------------------------------------------------------------------
FOUND 31 ERRORS AND 1 WARNING AFFECTING 32 LINES
--------------------------------------------------------------------------------
  66 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
  67 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
  89 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 101 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 113 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 114 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 115 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 116 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 129 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 131 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 133 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 140 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 141 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 153 | WARNING | In footer ($in_footer) is not set explicitly
     |         | wp_enqueue_script; It is recommended to load scripts in the
     |         | footer. Please set this value to `true` to load it in the
     |         | footer, or explicitly `false` if it should be loaded in the
     |         | header.
     |         | (WordPress.WP.EnqueuedResourceParameters.NotInFooter)
 158 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 159 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 200 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 203 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 206 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 209 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 229 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 261 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 293 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 377 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 378 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 379 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 380 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 393 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 394 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 395 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 396 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
 397 | ERROR   | Mismatched text domain. Expected 'xsx-shorten-it' but got
     |         | 'xsx-short-it'. (WordPress.WP.I18n.TextDomainMismatch)
--------------------------------------------------------------------------------

FILE: ...p-plugin-review/xsx-shorten-it/vendor/splitbrain/php-qrcode/src/QRCode.php
--------------------------------------------------------------------------------
FOUND 50 ERRORS AFFECTING 50 LINES
--------------------------------------------------------------------------------
  60 | ERROR | [x] The static declaration must come after the visibility
     |       |     declaration
     |       |     (PSR2.Methods.MethodDeclaration.StaticBeforeVisibility)
 201 | ERROR | [ ] There must be a comment when fall-through is intentional in
     |       |     a non-empty case body
     |       |     (PSR2.ControlStructures.SwitchDeclaration.TerminatingComment)
 204 | ERROR | [ ] There must be a comment when fall-through is intentional in
     |       |     a non-empty case body
     |       |     (PSR2.ControlStructures.SwitchDeclaration.TerminatingComment)
 222 | ERROR | [ ] There must be a comment when fall-through is intentional in
     |       |     a non-empty case body
     |       |     (PSR2.ControlStructures.SwitchDeclaration.TerminatingComment)
 226 | ERROR | [ ] There must be a comment when fall-through is intentional in
     |       |     a non-empty case body
     |       |     (PSR2.ControlStructures.SwitchDeclaration.TerminatingComment)
 246 | ERROR | [ ] There must be a comment when fall-through is intentional in
     |       |     a non-empty case body
     |       |     (PSR2.ControlStructures.SwitchDeclaration.TerminatingComment)
 249 | ERROR | [ ] There must be a comment when fall-through is intentional in
     |       |     a non-empty case body
     |       |     (PSR2.ControlStructures.SwitchDeclaration.TerminatingComment)
 299 | ERROR | [ ] There must be a comment when fall-through is intentional in
     |       |     a non-empty case body
     |       |     (PSR2.ControlStructures.SwitchDeclaration.TerminatingComment)
 337 | ERROR | [ ] There must be a comment when fall-through is intentional in
     |       |     a non-empty case body
     |       |     (PSR2.ControlStructures.SwitchDeclaration.TerminatingComment)
 340 | ERROR | [ ] There must be a comment when fall-through is intentional in
     |       |     a non-empty case body
     |       |     (PSR2.ControlStructures.SwitchDeclaration.TerminatingComment)
 776 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 778 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 780 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 782 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 784 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 786 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 788 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 790 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 792 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 794 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 796 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 798 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 800 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 802 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 804 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 806 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 808 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 810 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 812 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 814 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 816 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 818 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 820 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 822 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 824 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 826 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 828 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 830 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 832 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 834 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 836 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 838 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 840 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 842 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 844 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 846 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 848 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 850 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 852 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
 854 | ERROR | [x] Closing parenthesis of array declaration must be on a new
     |       |     line
     |       |     (WordPress.Arrays.ArrayDeclarationSpacing.CloseBraceNewLine)
--------------------------------------------------------------------------------
PHPCBF CAN FIX THE 41 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------

FILE: ...-plugin-review/xsx-shorten-it/vendor/splitbrain/php-qrcode/qrcode-test.php
--------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
--------------------------------------------------------------------------------
 39 | ERROR | All output should be run through an escaping function (see the
    |       | Security sections in the WordPress Developer Handbooks), found
    |       | 'substr'. (WordPress.Security.EscapeOutput.OutputNotEscaped)
 43 | ERROR | All output should be run through an escaping function (see the
    |       | Security sections in the WordPress Developer Handbooks), found
    |       | 'QRCode'. (WordPress.Security.EscapeOutput.OutputNotEscaped)
--------------------------------------------------------------------------------

FILE: /var/www/html/cp-plugin-review/xsx-shorten-it/vendor/autoload.php
--------------------------------------------------------------------------------
FOUND 2 ERRORS AND 2 WARNINGS AFFECTING 4 LINES
--------------------------------------------------------------------------------
 12 | WARNING | File operations should use WP_Filesystem methods instead of
    |         | direct PHP filesystem calls. Found: fwrite()
    |         | (WordPress.WP.AlternativeFunctions.file_system_read_fwrite)
 14 | ERROR   | All output should be run through an escaping function (see the
    |         | Security sections in the WordPress Developer Handbooks), found
    |         | '$err'. (WordPress.Security.EscapeOutput.OutputNotEscaped)
 17 | WARNING | trigger_error() found. Debug code should not normally be used
    |         | in production.
    |         | (WordPress.PHP.DevelopmentFunctions.error_log_trigger_error)
 18 | ERROR   | All output should be run through an escaping function (see the
    |         | Security sections in the WordPress Developer Handbooks), found
    |         | '$err'. (WordPress.Security.EscapeOutput.OutputNotEscaped)
--------------------------------------------------------------------------------

FILE: ...w/html/cp-plugin-review/xsx-shorten-it/vendor/composer/autoload_static.php
--------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
--------------------------------------------------------------------------------
 19 | ERROR | String concat is not required here; use a single string
    |       | instead (Generic.Strings.UnnecessaryStringConcat.Found)
 24 | ERROR | String concat is not required here; use a single string
    |       | instead (Generic.Strings.UnnecessaryStringConcat.Found)
--------------------------------------------------------------------------------

FILE: ...r/www/html/cp-plugin-review/xsx-shorten-it/vendor/composer/ClassLoader.php
--------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
--------------------------------------------------------------------------------
 500 | WARNING | Variable assignment found within a condition. Did you mean to
     |         | do a comparison?
     |         | (WordPress.CodeAnalysis.AssignmentInCondition.FoundInWhileCondition)
--------------------------------------------------------------------------------

FILE: ...ml/cp-plugin-review/xsx-shorten-it/vendor/composer/autoload_namespaces.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 8 | ERROR | [x] Empty array declaration must have no space between the
   |       |     parentheses
   |       |     (WordPress.Arrays.ArrayDeclarationSpacing.SpaceInEmptyArray)
--------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------

FILE: ...html/cp-plugin-review/xsx-shorten-it/vendor/composer/InstalledVersions.php
--------------------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 1 LINE
--------------------------------------------------------------------------------
 264 | WARNING | Silencing errors is strongly discouraged. Use proper error
     |         | checking instead. Found: @trigger_error('getRawData only
     |         | returns the first dataset loaded, which may not be what you
     |         | expect. Use getAllRawData() instead which returns all datasets
     |         | for all autoloaders present in the process.',
     |         | E_USER_DEPRECATED)...
     |         | (WordPress.PHP.NoSilencedErrors.Discouraged)
 264 | WARNING | trigger_error() found. Debug code should not normally be used
     |         | in production.
     |         | (WordPress.PHP.DevelopmentFunctions.error_log_trigger_error)
--------------------------------------------------------------------------------

**Comment by xxsimoxx** [comment]
Closing as `cpcs` is now passing.
